---
- name: Installing Docker and Jenkins on EC2
  hosts: locahost
  become: yes
  tasks:
    - name: Upgrade packages
      shell: |
        sudo apt update
        sudo apt upgrade -y

    - name: Install Jenkins
      shell: |
        sudo apt install -y openjdk-11-jdk
        wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
        sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5BA31D57EF5975CA
        sudo apt update
        sudo apt install -y jenkins
        sudo service jenkins start
        sudo systemctl status jenkins

    - name: Install Docker
      shell: |
        sudo apt install -y docker.io
        sudo groupadd docker
        sudo usermod -aG docker ubuntu

    - name: Add extra privileges to run Docker on Jenkins
      shell: |
        sudo usermod -aG docker jenkins
        sudo chmod 777 /var/run/docker.sock
        sudo service jenkins restart
